#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080
#define LARGURA_CANO 100
#define ALTURA_BURACO 300
#define DISTANCIA_ENTRE_CANOS 100
#define MARGEM_TOPO_BASE 4
#define VELOCIDADE_CANO 5
#define MAX_HISTORICO 10


#define GRAVIDADE 0.8f
#define FORCA_PULO -12.0f
#define VELOCIDADE_MAX 15.5f

#endif 